# Server Configuration
server.port=8080

# In-Memory H2 Database (Cloud & Local Ready)
spring.datasource.url=jdbc:h2:mem:frauddb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.h2.console.enabled=true

# JPA / Hibernate Configuration
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Python ML Microservice Live Endpoint
python.service.url=https://sentinel-ai-ml.onrender.com